### ISSUE TITLE
coq-scripts submodule not up to date with VDFILE

### ISSUE THREAD

**Issue by SkySkimmer** [mit-plv/fiat#10]
I have no idea how this passed CI.

**Comment by JasonGross** [comment]
Did it stop passing the CI?  We do a lot of fancy things with .v.d files for some targets, but I imagine the special handling code silently becomes a no-op with vdfile, and since we're not using it heavily for target selection like fiat-crypto does with the lite target, we probably just don't notice.

**Comment by SkySkimmer** [comment]
I've been having timeouts like https://travis-ci.org/SkySkimmer/coq/jobs/320260231 but I don't know if it's related (the coq/coq job for the same commit succeeded)
